I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 288, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\main.py", line 637, in main
    run(restart)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 288, in script
    python:
  File "C:\Users\Nani\Downloads\renpy-8.2.3-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
 
Wed Jul 24 23:08:13 2024
